#   ____                   _
#  |  _ \    ___   __  __ (_)
#  | |_) |  / _ \  \ \/ / | |
#  |  _ <  | (_) |  >  <  | |
#  |_| \_\  \___/  /_/\_\ |_|
#         C O N F I G
#

log-level: debug
port: 4000

########### PACKAGE MANAGER ###########
# handles plugin dependencies
package-manager: pnpm

plugins:
  - routify:
  - rollup:
      prod: true
      dev: false
      # port: 3000
  - '@roxi/plugin-mdsvex':
      extensions:
        - .md
        - .svx
  - '@roxi/plugin-postcss'
  - vite:
  - nollup:
      port: 3100
